# Generated by Django 5.1.4 on 2024-12-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_task_trask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='trask',
        ),
    ]
